### ISSUE TITLE
Light Rail / Tram fares now available for Opal

### ISSUE THREAD

**Issue by micolous** [jpatokal/opal_or_not#15]
The Light Rail / Tram system now has Opal, as at December 1.  Fare information:

https://www.opal.com.au/en/fares-and-benefits/fare_information_light_rail/

Fares appear to be calculated "as the crow flies" distances between stations.  The given example of Central - Glebe is approximately 4.5km by rail, but 1.8km point-to-point.

The advertising is misleading -- it doesn't take into account the weekly ticket (23$) or former annual ticket (948$).  Both of these tickets allow travel in all "zones".

If you travel to Central from further than Jubilee Park, this is a >3km journey and now costs more on Opal (28$/wk instead of 23$/wk on weekly paper tickets).

Old ticketing details:

http://web.archive.org/web/20140803141437/http://www.transportnsw.info/sites/en/tickets/ticket-types/light-rail.page

**Comment by jpatokal** [comment]
Implemented and pushed!  Both paper and Opal/distance fares should be accurate now.
